<?php

namespace App\Filament\Admin\Resources\AiGenerations\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class AiGenerationsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->defaultSort('created_at', 'desc')

            ->columns([

                TextColumn::make('provider')
                    ->badge()
                    ->searchable(),

                TextColumn::make('type')
                    ->badge()
                    ->searchable(),

                TextColumn::make('model')
                    ->searchable(),

                TextColumn::make('prompt')
                    ->limit(50)
                    ->searchable(),

                TextColumn::make('tokens_used')
                    ->label('Tokens')
                    ->numeric()
                    ->sortable(),

                TextColumn::make('user.name')
                    ->label('Generated By')
                    ->searchable(),

                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable(),

            ])

            ->filters([
                //
            ])

            ->recordActions([
                ViewAction::make(),
            ])

            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
